### ISSUE TITLE
Inure TODO List

### ISSUE THREAD

**Issue by Hamza417** [Hamza417/Inure#63]
**Note:** _Not all tasks has to be worked on._

- [x] Improve analytics panel
- [x] Add sub analytics panel
- [ ] Add galaxy store option in app info
- [ ] Add my email in about section
- [ ] Option for feedbacks right from the app
- [ ] Word on app documentation
- [x] Fix media notification buttons.
- [x] Add Shizuku support.
- [x] Add proper trial info screen.
- [x] Patch trial vulnerability.
- [x] Encrypted Shared Preferences.
- [x] Add proper permission status dialog.
- [ ] Add more info in batter optimization dialog.
- [x] Add option to skip setup panel permanently.
- [x] Remove device admin permissions and related elements.
- [x] Fix *Add Shortcut* in Terminal.
- [x] Fix _Initial Command_ not working on Shortcut.
- [x] Fix Terminal windows' manager issues and crashes.
- [x] Add terminal command manager.
- [x] Add better apps data generator.
- [x] Fix Music bugs.
- [x] Fix Usage Stats data inconsistency issues.
- [ ] Add more context to each panel?
- [ ] Put themes under premium.
- [x] Fix seekbar glitches (smoothen their animations).
- [x] Put accent colors under premium.
- [x] Put transitions and arc type under premium.
- [ ] Put shortcuts under premium.
- [x] Put accessibility dividers under premium.
- [x] Put terminal and shell preferences under premium.
- [x] Put trackers preferences under premium.
- [ ] Put accessibility context menu under premium.
- [x] Put development preferences under premium.
- [ ] Put uninstalled apps under premium.
- [x] Hide tracker dialog on non premium.
- [ ] Put image viewer under premium.
- [x] Put notes editor under premium.
- [x] Put deep search under premium.
- [x] Fix corner radius going back bug.
- [ ] Reset settings after trial period.
- [x] Add High Contrast theme for Light mode.
- [x] Add Unlocker dev signature verification.
- [ ] Implement a valid global popup position framework and rid of view anchors.
- [ ] Add Play Store installer detection.
- [x] Add notes not saved warning.
- [x] Fix unlocker detection issues.
- [x] Add option to disable tracker activities.
- [x] Add graph based Usage Stats panel.
- [ ] Add app categories panel.
- [x] Fix app disable global state.
- [ ] Create a local database for uninstalled apps.
- [x] Fix audio player issues.
- [ ] Add dynamic buttons resizer.
- [ ] Add option to upload apps on APKMirror.
- [ ] Add support for xAPK files.
- [x] Add option to hide apps
- [x] Add an Inure level Audio Player.
- [x] Fix bottom bar not getting clipped issue.
- [x] Add auto unlocker detection.
- [ ] Add global data re-fetch framework upon any runtime data mutation.
- [x] Make some animations smoother (app's framework needs more optimization).
- [x] Add sort and filter in boot manager.
- [x] Find source of cannot connect to main shell error.
- [x] Fix disabled apps indicator color on different themes.
- [x] Add more context in Batch
- [ ] Add `market` redirect to Inure?
- [x] Fix missing TTF files from Extras.
- [ ] Add application flags in App Info panel.
- [ ] Better warning system in Preferences.
- [x] Fix Russian locale and app layout issues.
- [x] Add component manager in Boot Manager
- [ ] Multiple item selection in various panels.
- [x] Add better interface for Battery Optimization.
- [x] Add repeat button.
- [x] Add option to enable context in bottom menu
- [x] Fix empty trackers' panel in installer section
- [x] Remove Inure from batch
- [x] Fix searched item missing bug
- [x] Check marshmallow Russian issue
- [x] Added no trackers found warning
- [x] Fix Marshmallow errors
- [x] Fix root denied loader block
- [x] Fix crash handler missing error report
- [x] Make home screen refresh after the settings has changed.
- [x] Add battery optimization.
- [x] Add DUMP permission.
- [x] Open HTML in XML Viewer panel.
